//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Hide.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_TRIAL_DIALOG                102
#define IDD_PPAGECOMMON                 103
#define IDD_PPAGEPERFOMANCE             104
#define IDD_PPAGEAPPMENU                105
#define IDD_SPLASHWINDOW                106
#define IDR_MAINFRAME                   128
#define IDR_HIDETYPE                    129
#define IDM_POPUPMENUICON               129
#define IDM_APP_MENU                    130
#define IDC_CURSORHARROW                130
#define IDI_SHOWALL                     131
#define IDI_HIDEALL                     132
#define IDI_CHECK_LARGE                 133
#define IDI_HIDEALL_SMALL               135
#define IDI_CHECK_SMALL                 136
#define IDB_MENU_TITLE                  137
#define IDI_SHOWALL_SMALL               137
#define IDI_TRAYFULL                    141
#define IDD_REG_DIALOG                  142
#define IDD_PPAGEHIDE                   143
#define IDD_PPAGEHOTKEYS                144
#define IDD_PPAGEPASSWORDS              145
#define IDD_PASSWORDDIALOG              146
#define IDI_TRAYICON                    147
#define IDI_TRAYEMPTY                   147
#define IDD_WNDPARMLIST                 147
#define IDI_EMPTY                       148
#define IDD_PPAGEWNDMAIN                149
#define IDD_WNDPPAGEHIDE                150
#define IDD_WNDPPAGEPASSWORDS           151
#define IDD_WNDPPAGEPERFOMANCE          152
#define IDM_WNDMENU                     153
#define IDC_REGINFO                     1000
#define IDC_MENU_ICONTYPE               1001
#define IDC_CLIENTINFO                  1001
#define IDC_BUYNOW                      1001
#define IDC_STATIC1                     1001
#define IDC_HIDE_MINIMIZE               1002
#define IDC_TRIMCAPTION                 1002
#define IDC_REG_BUTTON                  1002
#define IDC_PROCESSINVISIBLEWND         1003
#define IDC_ADDSHOWALL                  1003
#define IDC_REGNUM_EDIT                 1003
#define IDC_MOUSEHIDE                   1003
#define IDC_HOTKEYMAIN                  1003
#define IDC_SPLASHWINDOW                1004
#define IDC_SHOWAPP                     1004
#define IDC_ADDHIDEALL                  1005
#define IDC_REDUCEMEMORY                1006
#define IDC_EXTRACTICONFROMEXE          1006
#define IDC_AUTOSTART                   1006
#define IDC_PASTE                       1006
#define IDC_HIDEALLWNDAPP               1006
#define IDC_ACTIONLIST                  1006
#define IDC_ACTIVATENEXT                1006
#define IDC_REDUCEALLMEMORY             1007
#define IDC_SOFTEXIT                    1007
#define IDC_ACTIONLISTHK                1007
#define IDC_MOUSEHIDEDBL                1007
#define IDC_EMAIL                       1008
#define IDC_STATICOPT                   1008
#define IDC_ADDHIDE                     1008
#define IDC_HIDE_CREATE                 1008
#define IDC_WNDMENU                     1008
#define IDC_INTERNET                    1009
#define IDC_STATICOPTALL                1009
#define IDC_RADIOHIDETO                 1010
#define IDC_CHANGEPRIORITY              1010
#define IDC_RADIOHIDETO_TRAY            1011
#define IDC_CHANGEPRIORITYPM            1011
#define IDC_INFO                        1012
#define IDC_RADIOHIDETO_MENUTRAY        1012
#define IDC_PROCESSPRIORITY             1012
#define IDC_TRIMCHARS                   1013
#define IDC_PRIORITY_NORMAL             1013
#define IDC_RADIOHIDETO_PRIVATEMENU     1013
#define IDC_PRIORITY_LOW                1014
#define IDC_RADIOHIDETO_PRIVATEMENUCOMMON 1014
#define IDC_MEMOPTGROUP                 1015
#define IDC_PRIORITYGROUP               1016
#define IDC_RADIOHIDEMETHOD             1017
#define IDC_RADIOHIDEMETHOD2            1018
#define IDC_DELAYCOMBOHIDDEN            1019
#define IDC_RADIOHIDEMETHOD3            1019
#define IDC_REGISTER                    1019
#define IDC_MASTERPWD                   1020
#define IDC_RADIOHIDEMETHOD4            1020
#define IDC_DELAYCOMBOHIDDENALL         1021
#define IDC_MASTERPWDCONFIRM            1021
#define IDC_PWDUSEEXIT                  1023
#define IDC_PWDUSESETTINGS              1024
#define IDC_PWDUSESHOWMENU              1025
#define IDC_PWDUSESHOWWINDOW            1026
#define IDC_PWDUSESHOWPRIVATEMENU       1027
#define IDC_MASTERBOX                   1028
#define IDC_GROUPBOX                    1029
#define IDC_PWDUSEWNDSETTINGS           1031
#define IDC_WNDLIST                     1037
#define IDC_WNDNAME                     1039
#define IDC_EXENAME                     1040
#define IDC_WNDICON                     1041
#define IDC_RESTOREBUTTON               1042
#define IDC_CLEARBUTTON                 1044
#define IDC_WNDLSTDELETE                1045
#define IDC_WNDLSTEDIT                  1046
#define IDC_CLEAREXEBUTTON              1047
#define IDC_FINDBUTTON                  1048
#define IDM_EXIT                        32771
#define IDM_WNDSETTINGS                 32772
#define IDM_HIDEWND                     32774
#define IDM_CUSTOMWNDSETTINGS           32776
#define IDM_SETTINGS                    32777
#define IDM_SHOWALL                     32778
#define IDM_HIDEALL                     32779
#define IDM_WNDSETTINGSPOPUP            32780
#define IDM_SETTINGSPOPUP               32781
#define IDS_APPMENUHIDEALL              57347
#define IDS_APPMENUSHOWALL              57348
#define IDC_SPLASHICON                  65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
